### ISSUE TITLE
Stroke line join produces an artifact

### ISSUE THREAD

**Issue by RazrFalcon** [jrmuizel/raqote#41] opened 2019-05-14 18:05 UTC
You can see a transparent "triangle" here:

![out](https://user-images.githubusercontent.com/725494/57721088-fbe2fe80-768b-11e9-9f48-08d004772449.png)

- `M 40 70 l 80 20 l -80 20`
- stroke-width="30"
- stroke-linecap="miter"

**Comment by jrmuizel** [comment] 2019-05-14 18:10
This is duplicate of #6

**Closed** 2019-05-14 18:09 UTC
